export const FETCH_CATEGORY_INIT = "FETCH_CATEGORY_INIT";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_ERROR = "FETCH_CATEGORY_ERROR";
export const SET_CATEGORY_ID = "SET_CATEGORY_ID";

export const FETCH_PRODUCT_INIT = "FETCH_PRODUCT_INIT";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";

export const INCREMENT_QTY = "INCREMENT_QTY";
export const DECREMENT_QTY = "DECREMENT_QTY";
